services:
  scheduler:
    volumes:
      - ./dbt_dw/:/usr/local/airflow/dbt/dbt_dw
      - ./scraper/:/usr/local/airflow/scraper
      - ./data/:/usr/local/airflow/data
  dag-processor:
    volumes:
      - ./dbt_dw/:/usr/local/airflow/dbt/dbt_dw
      - ./scraper/:/usr/local/airflow/scraper
      - ./data/:/usr/local/airflow/data